### ISSUE TITLE
Log

### ISSUE THREAD

**Issue by ExperienceUK** [khromov/sitemap-cache-warmer#14]
Just testing this on a magento site with 2 sitemaps containing approx 90,000 URLs

1. Is it possible to log to a text file on the server?
2. Is it possible to check if the script is already running i.e. make sure script is not already running so multiple scripts are not running at the same time?

**Comment by khromov** [comment]
Hey @ExperienceUK 

1. It should work fine if you use the CLI and pipe to a file, something like:

```
php /whatever/you/have/uploaded/it/warm.php url=http://example.com/sitemap.xml sleep=0 key=SECRET_KEY > mylogfile.log
```

See: https://github.com/khromov/sitemap-cache-warmer/tree/master#using-the-cli

2. There is no such mechanism currently, the script has no persistence. You can use something like `flock` or any other native unix way of handling it:
https://serverfault.com/questions/82857/prevent-duplicate-cron-jobs-running

You could also make a pull request to add the functionality in the script itself if you're up for it!

**Comment by ExperienceUK** [comment]
great, thanks
