### ISSUE TITLE
How to define a User Agent?

### ISSUE THREAD

**Issue by marius-zenitech** [khromov/sitemap-cache-warmer#3]
Any suggestion where I can define a custom user agent that the crawler will use?

**Comment by khromov** [comment]
Hi @Sorasma 

You would have to add the `User-Agent` header to the stream context used for requests, here: 
https://github.com/khromov/sitemap-cache-warmer/blob/master/class/PHP_Warmer.class.php#L26

Here is some info on adding a `User-Agent` header:
https://stackoverflow.com/a/13969212
