### ISSUE TITLE
Repetition/duplicating processes

### ISSUE THREAD

**Issue by sam-fc** [khromov/sitemap-cache-warmer#5]
I have been running this script for awhile and never had a problem. I updated wordpress to the latest 4.9.5 (don't know if it's the issue ) so when I run it manually :

http://example.com/warm-cache/warm.php?key=SECRET_KEY&url=http://example.com/sitemap.xml&sleep=0

it starts fine but ends up creating a bunch of duplicate/new processes without finishing the first one(s).

xxxxx 313182 313181 0 17:52 pts/1 00:00:00 -bash
xxxxx 382580 352882 2 18:04 ? 00:00:01 /usr/bin/php /home/xxxxx/public_html/index.php
xxxxx 382811 352882 2 18:04 ? 00:00:01 /usr/bin/php /home/xxxxx/public_html/index.php
xxxxx 382966 382409 2 18:04 ? 00:00:01 /usr/bin/php /home/xxxxx/public_html/index.php
xxxxx 383147 382409 3 18:04 ? 00:00:01 /usr/bin/php /home/xxxxx/public_html/index.php
xxxxx 384288 378013 2 18:04 ? 00:00:00 /usr/bin/php /home/xxxxx/public_html/index.php
xxxxx 384325 365556 2 18:04 ? 00:00:00 /usr/bin/php /home/xxxxx/public_html/index.php
xxxxx 384560 366217 2 18:04 ? 00:00:00 /usr/bin/php /home/xxxxx/public_html/index.php
xxxxx 384932 382409 3 18:05 ? 00:00:00 /usr/bin/php /home/xxxxx/public_html/index.php
xxxxx 385007 382409 3 18:05 ? 00:00:00 /usr/bin/php /home/xxxxx/public_html/index.php
xxxxx 385961 365556 2 18:05 ? 00:00:00 /usr/bin/php /home/xxxxx/public_html/index.php
xxxxx 386260 352882 2 18:05 ? 00:00:00 /usr/bin/php /home/xxxxx/public_html/index.php
xxxxx 386493 366217 3 18:05 ? 00:00:00 /usr/bin/php /home/xxxxx/public_html/index.php
xxxxx 386750 366217 3 18:05 ? 00:00:00 /usr/bin/php /home/xxxxx/public_html/index.php
xxxxx 386766 370523 3 18:05 ? 00:00:00 /usr/bin/php /home/xxxxx/public_html/index.php
xxxxx 387095 366217 3 18:05 ? 00:00:00 /usr/bin/php /home/xxxxx/public_html/index.php
xxxxx 387661 386962 4 18:05 ? 00:00:00 /usr/bin/php /home/xxxxx/public_html/index.php
xxxxx 387770 313182 0 18:05 pts/1 00:00:00 ps -eaf
xxxxx 450783 426590 0 15:17 ? 00:00:01 /usr/bin/php /home/xxxxx/public_html/warm-cache/warm.php
459438 349316 0 15:19 ? 00:00:01 /usr/bin/php /home/xxxxx/public_html/warm-cache/warm.php
469428 426590 0 15:20 ? 00:00:01 /usr/bin/php /home/xxxxx/public_html/warm-cache/warm.php
 481115 474173 0 15:22 ? 00:00:01 /usr/bin/php /home/xxxxx/public_html/warm-cache/warm.php
489999 485712 0 15:24 ? 00:00:01 /usr/bin/php /home/xxxxx/public_html/warm-cache/warm.php
 500437 491531 0 15:25 ? 00:00:01 /usr/bin/php /home/xxxxx/public_html/warm-cache/warm.php
xxxxx 511611 506407 0 15:27 ? 00:00:01 /usr/bin/php /home/xxxxx/public_html/warm-cache/warm.php
 520966 506407 0 15:29 ? 00:00:01 /usr/bin/php /home/xxxxx/public_html/warm-cache/warm.php
 532830 529028 0 15:30 ? 00:00:01 /usr/bin/php /home/xxxxx/public_html/warm-cache/warm.php
xxxxx 542480 529028 0 15:32

resources go through the roof and doesn't crate the pages in cache .

Will update if a solution for the issue(?) is found . Please let us know if you have any thoughts of could be causing the issue. 
?????

**Comment by prcwest** [comment]
hello

is there any update?

**Comment by sam-fc** [comment]
Yes , I think I replied and mentioned that if I didn't close the window the timeouts from cloudflare would reinitiate the processes , so all I have to do is run the url and make sure I close the window , this way it works
