### ISSUE TITLE
Question: Can I crawl another url?

### ISSUE THREAD

**Issue by madesimplemedia** [khromov/sitemap-cache-warmer#7]
Hi

Can the script crawl another url e.g.

wget "http://example.com/warm-cache/warm.php?key=SECRET_KEY&url=http://anothersite.com/sitemap.xml&sleep=0"

**Comment by khromov** [comment]
Yes, you can crawl any publicly available sitemap.

**Comment by madesimplemedia** [comment]
Thank you :)
